const level1 = new Level(
  [new Chicken(), new Chicken(), new Chicken(), new ChickenSmall(), new ChickenSmall(), new ChickenSmall()],
  [new Cloud('./img/5_background/layers/4_clouds/1.png')],
  [
    new BackgroundObject('./img/5_background/layers/air.png', 0),
    new BackgroundObject('./img/5_background/layers/3_third_layer/1.png', 0),
    new BackgroundObject('./img/5_background/layers/2_second_layer/1.png', 0),
    new BackgroundObject('./img/5_background/layers/1_first_layer/1.png', 0),
    new BackgroundObject('./img/5_background/layers/air.png', 720),
    new BackgroundObject('./img/5_background/layers/3_third_layer/2.png', 720),
    new BackgroundObject('./img/5_background/layers/2_second_layer/2.png', 720),
    new BackgroundObject('./img/5_background/layers/1_first_layer/2.png', 720),
    new BackgroundObject('./img/5_background/layers/air.png', 1440),
    new BackgroundObject('./img/5_background/layers/3_third_layer/1.png', 1440),
    new BackgroundObject('./img/5_background/layers/2_second_layer/1.png', 1440),
    new BackgroundObject('./img/5_background/layers/1_first_layer/1.png', 1440),
    new BackgroundObject('./img/5_background/layers/air.png', 2160),
    new BackgroundObject('./img/5_background/layers/3_third_layer/2.png', 2160),
    new BackgroundObject('./img/5_background/layers/2_second_layer/2.png', 2160),
    new BackgroundObject('./img/5_background/layers/1_first_layer/2.png', 2160),
    new BackgroundObject('./img/5_background/layers/air.png', 720 * 4),
    new BackgroundObject('./img/5_background/layers/3_third_layer/1.png', 720 * 4),
    new BackgroundObject('./img/5_background/layers/2_second_layer/1.png', 720 * 4),
    new BackgroundObject('./img/5_background/layers/1_first_layer/1.png', 720 * 4),
    new BackgroundObject('./img/5_background/layers/air.png', 720 * 5),
    new BackgroundObject('./img/5_background/layers/3_third_layer/2.png', 720 * 5),
    new BackgroundObject('./img/5_background/layers/2_second_layer/2.png', 720 * 5),
    new BackgroundObject('./img/5_background/layers/1_first_layer/2.png', 720 * 5),
  ],
  [new Bottle(), new Bottle(), new Bottle(), new Bottle(), new Bottle()],
  [
    new Coin(400, 300),
    new Coin(850, 200),
    new Coin(900, 180),
    new Coin(950, 160),
    new Coin(1000, 160),
    new Coin(1050, 180),
    new Coin(2250, 200),
    new Coin(2300, 200),
    new Coin(2350, 200),
    new Coin(2400, 200),
  ],
);
